import 'server-only'

/**
 * AryTrano — PaymentProvider abstraction (E-T15).
 *
 * Designed against the real GoalPay API surface (verified 2026-05-25
 * via https://goalpay.pro/docs/api/integrations). The provider has:
 *
 *   - ONE init endpoint                       → `initiate()`
 *   - Webhook callbacks (4 events)            → `verifyWebhookSignature()` + `parseWebhook()`
 *   - NO refund API                           → omitted; refunds are manual via admin + GoalPay support
 *   - NO transaction lookup / status check    → omitted; we rely on webhook only
 *   - NO sandbox documented                   → testing happens in prod with minimal amounts
 *
 * Keeping the interface narrow (no `refund()`, no `lookup()`) prevents
 * us from leaking capabilities the provider doesn't actually have. If a
 * future provider supports them, we extend the interface with optional
 * methods or add a separate `RefundableProvider` extension.
 */

/** Server-side input to start a payment. */
export interface InitiatePaymentInput {
  /**
   * Our merchant-side reference. Generated by us (cuid), passed to
   * GoalPay's `reference` body field, echoed back in webhooks as
   * `data.reference`. Doubles as the idempotency anchor for webhook
   * lookups (must be UNIQUE in our DB).
   */
  reference: string
  /** Amount in Ariary (Int per memory project_mga_no_subunit). */
  amountMGA: number
  /** Description shown to the payer on the GoalPay checkout page. */
  description: string
  /**
   * Itemized breakdown shown on the checkout page. Each row will be
   * displayed line by line; the sum should equal `amountMGA`.
   */
  metadata: ReadonlyArray<{
    label: string
    unit_price: number
    quantity: number
  }>
}

export interface InitiatePaymentResult {
  /** GoalPay's `order_reference` — store in Payment.providerTxId. */
  providerTxId: string
  /** Hosted checkout URL — redirect the user here. */
  checkoutUrl: string
  /** TTL of the checkout link in minutes. GoalPay docs say 10. */
  expiresInMinutes: number
}

/**
 * The four webhook events GoalPay can send. Aligned with the spec's
 * `event` field values verbatim — do not reword.
 */
export type WebhookEventType =
  | 'payment.success'
  | 'payment.failed'
  | 'payment.canceled'
  | 'payment.expired'

export interface WebhookEvent {
  event: WebhookEventType
  /** GoalPay's `order_reference` (matches Payment.providerTxId). */
  orderReference: string
  /** Our reference echoed back (matches Payment.idempotencyKey). */
  reference: string
  /** Amount in Ariary (Int). */
  amountMGA: number
  /** Currency code, always `"Ar"` per GoalPay. */
  currency: string
  /** Original description from initiation. */
  description: string
  /** Optional error message — present on failed/canceled/expired events. */
  error?: string
}

/**
 * Minimal payment provider contract — matches what GoalPay actually
 * supports. Other Mobile Money providers in MG (Voaray, Efaina, Papi,
 * Orange Money direct) can implement this same surface.
 */
export interface PaymentProvider {
  /** Start a checkout session. Returns the hosted URL to redirect to. */
  initiate(input: InitiatePaymentInput): Promise<InitiatePaymentResult>
  /**
   * Verify the inbound webhook signature using the provider-specific
   * scheme (GoalPay: HMAC-SHA256 of raw body, header `x-gpay-signature`).
   * Implementation MUST use a timing-safe comparison.
   */
  verifyWebhookSignature(rawBody: string, signature: string | null): boolean
  /**
   * Parse a verified webhook body into a typed event. Throws if the
   * payload doesn't match the expected schema (caller catches → 400).
   */
  parseWebhook(rawBody: string): WebhookEvent
}
