-- CreateEnum
CREATE TYPE "Amenity" AS ENUM ('WIFI', 'PARKING', 'MOTO_PARKING', 'HOT_WATER', 'WATER_TANK', 'GENERATOR', 'AIR_CONDITIONING', 'KITCHEN_EQUIPPED', 'WASHING_MACHINE', 'GUARD', 'SECURITY_GATE', 'TERRACE', 'GARDEN', 'STUDY_DESK', 'CLOSE_TO_UNIVERSITY', 'CLOSE_TO_MARKET', 'PUBLIC_TRANSPORT');

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "amenities" "Amenity"[] DEFAULT ARRAY[]::"Amenity"[];
